from scrapper import get_processed_data, create_new_format


def test_create_new_format_key_existence():
    new_format = create_new_format()
    assert 'datasource' in new_format
    assert 'dataset_type' in new_format
    assert 'dataset_id' in new_format
    assert 'time_object' in new_format
    assert 'events' in new_format
    assert 'timestamp' in new_format['time_object']
    assert 'timezone' in new_format['time_object']


def test_create_new_format_value_correctness():
    new_format = create_new_format()
    assert new_format['datasource'] == 'Australian Government Bureau of Meteorology'
    assert new_format['dataset_type'] == 'weather_info'
    assert new_format['dataset_id'] == 'http://reg.bom.gov.au/fwo/IDN60901/IDN60901.94768.json'
    assert new_format['time_object'] is not None
    assert new_format['time_object']['timestamp'] is not None
    assert new_format['time_object']['timezone'] is not None
    assert new_format['events'] == []


def test_get_processed_data_all_null():
    origin_object = {
        "observations": {
            "data": [
                {
                    "sort_order": None,
                    "wmo": None,
                    "name": None,
                    "history_product": None,
                    "local_date_time": None,
                    "local_date_time_full": None,
                    "aifstime_utc": None,
                    "lat": None,
                    "lon": None,
                    "apparent_t": None,
                    "cloud": None,
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": None,
                    "delta_t": None,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": None,
                    "dewpt": None,
                    "press": None,
                    "press_qnh": None,
                    "press_msl": None,
                    "press_tend": None,
                    "rain_trace": None,
                    "rel_hum": None,
                    "sea_state": None,
                    "swell_dir_worded": None,
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": None,
                    "weather": None,
                    "wind_dir": None,
                    "wind_spd_kmh": None,
                    "wind_spd_kt": None
                },
                {
                    "sort_order": None,
                    "wmo": None,
                    "name": None,
                    "history_product": None,
                    "local_date_time": None,
                    "local_date_time_full": None,
                    "aifstime_utc": None,
                    "lat": None,
                    "lon": None,
                    "apparent_t": None,
                    "cloud": None,
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": None,
                    "delta_t": None,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": None,
                    "dewpt": None,
                    "press": None,
                    "press_qnh": None,
                    "press_msl": None,
                    "press_tend": None,
                    "rain_trace": None,
                    "rel_hum": None,
                    "sea_state": None,
                    "swell_dir_worded": None,
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": None,
                    "weather": None,
                    "wind_dir": None,
                    "wind_spd_kmh": None,
                    "wind_spd_kt": None
                },
                {
                    "sort_order": None,
                    "wmo": None,
                    "name": None,
                    "history_product": None,
                    "local_date_time": None,
                    "local_date_time_full": None,
                    "aifstime_utc": None,
                    "lat": None,
                    "lon": None,
                    "apparent_t": None,
                    "cloud": None,
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": None,
                    "delta_t": None,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": None,
                    "dewpt": None,
                    "press": None,
                    "press_qnh": None,
                    "press_msl": None,
                    "press_tend": None,
                    "rain_trace": None,
                    "rel_hum": None,
                    "sea_state": None,
                    "swell_dir_worded": None,
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": None,
                    "weather": None,
                    "wind_dir": None,
                    "wind_spd_kmh": None,
                    "wind_spd_kt": None
                },
            ],
        },
    }
    assert get_processed_data(origin_object)['observations']['data'] == [{
        'wmo': None,
        'name': None,
        'local_date_time': None,
        'apparent_temp': None,
        'cloud': None,
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': None,
        'pressure': None,
        'rain_trace_since_9am': None,
        'rel_humidity': None,
        'visibility_km': None,
        'wind_direction': None,
        'wind_speed_kmh': None
    }, {
        'wmo': None,
        'name': None,
        'local_date_time': None,
        'apparent_temp': None,
        'cloud': None,
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': None,
        'pressure': None,
        'rain_trace_since_9am': None,
        'rel_humidity': None,
        'visibility_km': None,
        'wind_direction': None,
        'wind_speed_kmh': None
    }, {
        'wmo': None,
        'name': None,
        'local_date_time': None,
        'apparent_temp': None,
        'cloud': None,
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': None,
        'pressure': None,
        'rain_trace_since_9am': None,
        'rel_humidity': None,
        'visibility_km': None,
        'wind_direction': None,
        'wind_speed_kmh': None
    }]


def test_get_processed_data_some_null():
    origin_object = {
        "observations": {
            "data": [
                {
                    "sort_order": 1,
                    "wmo": 94768,
                    "name": "Sydney - Observatory Hill",
                    "history_product": None,
                    "local_date_time": None,
                    "local_date_time_full": None,
                    "aifstime_utc": None,
                    "lat": None,
                    "lon": None,
                    "apparent_t": 23,
                    "cloud": None,
                    "cloud_base_m": None,
                    "cloud_oktas": 7,
                    "cloud_type_id": None,
                    "cloud_type": None,
                    "delta_t": None,
                    "gust_kmh": 16,
                    "gust_kt": None,
                    "air_temp": None,
                    "dewpt": None,
                    "press": 1014,
                    "press_qnh": None,
                    "press_msl": None,
                    "press_tend": None,
                    "rain_trace": None,
                    "rel_hum": 65,
                    "sea_state": None,
                    "swell_dir_worded": None,
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": None,
                    "weather": None,
                    "wind_dir": "N",
                    "wind_spd_kmh": 17,
                    "wind_spd_kt": None
                },
                {
                    "sort_order": None,
                    "wmo": None,
                    "name": None,
                    "history_product": None,
                    "local_date_time": None,
                    "local_date_time_full": None,
                    "aifstime_utc": None,
                    "lat": None,
                    "lon": None,
                    "apparent_t": None,
                    "cloud": None,
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": None,
                    "delta_t": None,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": None,
                    "dewpt": None,
                    "press": None,
                    "press_qnh": None,
                    "press_msl": None,
                    "press_tend": None,
                    "rain_trace": None,
                    "rel_hum": None,
                    "sea_state": None,
                    "swell_dir_worded": None,
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": None,
                    "weather": None,
                    "wind_dir": None,
                    "wind_spd_kmh": None,
                    "wind_spd_kt": None
                },
            ],
        },
    }

    assert get_processed_data(origin_object)['observations']['data'] == [{
        'wmo': 94768,
        'name': 'Sydney - Observatory Hill',
        'local_date_time': None,
        'apparent_temp': 23,
        'cloud': None,
        'cloud_oktas': 7,
        'gust_kmh': 16,
        'air_temp': None,
        'pressure': 1014,
        'rain_trace_since_9am': None,
        'rel_humidity': 65,
        'visibility_km': None,
        'wind_direction': 'N',
        'wind_speed_kmh': 17
    }, {
        'wmo': None,
        'name': None,
        'local_date_time': None,
        'apparent_temp': None,
        'cloud': None,
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': None,
        'pressure': None,
        'rain_trace_since_9am': None,
        'rel_humidity': None,
        'visibility_km': None,
        'wind_direction': None,
        'wind_speed_kmh': None
    }]


def test_get_processed_data_only_one_not_null():
    origin_object = {
        "observations": {
            "data": [
                        {
                            "sort_order": None,
                            "wmo": 94768,
                            "name": None,
                            "history_product": None,
                            "local_date_time": None,
                            "local_date_time_full": None,
                            "aifstime_utc": None,
                            "lat": None,
                            "lon": None,
                            "apparent_t": None,
                            "cloud": None,
                            "cloud_base_m": None,
                            "cloud_oktas": None,
                            "cloud_type_id": None,
                            "cloud_type": None,
                            "delta_t": None,
                            "gust_kmh": None,
                            "gust_kt": None,
                            "air_temp": None,
                            "dewpt": None,
                            "press": None,
                            "press_qnh": None,
                            "press_msl": None,
                            "press_tend": None,
                            "rain_trace": None,
                            "rel_hum": None,
                            "sea_state": None,
                            "swell_dir_worded": None,
                            "swell_height": None,
                            "swell_period": None,
                            "vis_km": None,
                            "weather": None,
                            "wind_dir": None,
                            "wind_spd_kmh": None,
                            "wind_spd_kt": None
                        },
            ],
        },
    }
    
    assert get_processed_data(origin_object)['observations']['data'] == [{
        'wmo': 94768,
        'name': None,
        'local_date_time': None,
        'apparent_temp': None,
        'cloud': None,
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': None,
        'pressure': None,
        'rain_trace_since_9am': None,
        'rel_humidity': None,
        'visibility_km': None,
        'wind_direction': None,
        'wind_speed_kmh': None
    }]


def test_get_processed_data_only_one_null():
    origin_object = {
        "observations": {
            "data": [
                {
                    "sort_order": 8,
                    "wmo": None,
                    "name": "Sydney - Observatory Hill",
                    "history_product": "IDN60901",
                    "local_date_time": "10/05:00pm",
                    "local_date_time_full": "20230410170000",
                    "aifstime_utc": "20230410070000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": 14.6,
                    "cloud": "-",
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": "-",
                    "delta_t": 5.4,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": 17.5,
                    "dewpt": 6.7,
                    "press": 1007.9,
                    "press_qnh": 1008.0,
                    "press_msl": 1007.9,
                    "press_tend": "-",
                    "rain_trace": "0.0",
                    "rel_hum": 49,
                    "sea_state": "-",
                    "swell_dir_worded": "-",
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": "-",
                    "weather": "-",
                    "wind_dir": "SSE",
                    "wind_spd_kmh": 11,
                    "wind_spd_kt": 6
                },
                {
                    "sort_order": 9,
                    "wmo": 94768,
                    "name": "Sydney - Observatory Hill",
                    "history_product": "IDN60901",
                    "local_date_time": "10/04:30pm",
                    "local_date_time_full": "20230410163000",
                    "aifstime_utc": "20230410063000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": 14.4,
                    "cloud": "-",
                    "cloud_base_m": None,
                    "cloud_oktas": None,
                    "cloud_type_id": None,
                    "cloud_type": "-",
                    "delta_t": 5.8,
                    "gust_kmh": None,
                    "gust_kt": None,
                    "air_temp": 17.8,
                    "dewpt": 6.0,
                    "press": 1007.7,
                    "press_qnh": 1007.8,
                    "press_msl": 1007.7,
                    "press_tend": "-",
                    "rain_trace": "0.0",
                    "rel_hum": 46,
                    "sea_state": "-",
                    "swell_dir_worded": "-",
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": "-",
                    "weather": "-",
                    "wind_dir": "SSE",
                    "wind_spd_kmh": 13,
                    "wind_spd_kt": 7
                },
            ],
        },
    }

    assert get_processed_data(origin_object)['observations']['data'] == [{
        'wmo': None,
        'name': 'Sydney - Observatory Hill',
        'local_date_time': '20230410170000',
        'apparent_temp': 14.6,
        'cloud': '-',
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': 17.5,
        'pressure': 1007.9,
        'rain_trace_since_9am': '0.0',
        'rel_humidity': 49,
        'visibility_km': '-',
        'wind_direction': 'SSE',
        'wind_speed_kmh': 11
    }, {
        'wmo': 94768,
        'name': 'Sydney - Observatory Hill',
        'local_date_time': '20230410163000',
        'apparent_temp': 14.4,
        'cloud': '-',
        'cloud_oktas': None,
        'gust_kmh': None,
        'air_temp': 17.8,
        'pressure': 1007.7,
        'rain_trace_since_9am': '0.0',
        'rel_humidity': 46,
        'visibility_km': '-',
        'wind_direction': 'SSE',
        'wind_speed_kmh': 13
    }]


def test_get_processed_data_all_not_null():
    origin_object = {
        "observations": {
            "data": [
                {
                    "sort_order": 7,
                    "wmo": 94767,
                    "name": "Sydney Airport",
                    "history_product": "IDN60901",
                    "local_date_time": "10/10:00pm",
                    "local_date_time_full": "20230410220000",
                    "aifstime_utc": "20230410120000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": 10.0,
                    "cloud": "Cloudy",
                    "cloud_base_m": 2160,
                    "cloud_oktas": 8,
                    "cloud_type_id": None,
                    "cloud_type": "-",
                    "delta_t": 4.8,
                    "gust_kmh": 24,
                    "gust_kt": 13,
                    "air_temp": 14.8,
                    "dewpt": 4.5,
                    "press": 1010.8,
                    "press_qnh": 1010.8,
                    "press_msl": 1010.8,
                    "press_tend": "-",
                    "rain_trace": "0.0",
                    "rel_hum": 50,
                    "sea_state": "-",
                    "swell_dir_worded": "-",
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": "10",
                    "weather": "-",
                    "wind_dir": "WSW",
                    "wind_spd_kmh": 19,
                    "wind_spd_kt": 10
                },
                {
                    "sort_order": 8,
                    "wmo": 94767,
                    "name": "Sydney Airport",
                    "history_product": "IDN60901",
                    "local_date_time": "10/09:30pm",
                    "local_date_time_full": "20230410213000",
                    "aifstime_utc": "20230410113000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": 10.1,
                    "cloud": "Cloudy",
                    "cloud_base_m": 2220,
                    "cloud_oktas": 8,
                    "cloud_type_id": None,
                    "cloud_type": "-",
                    "delta_t": 5.1,
                    "gust_kmh": 28,
                    "gust_kt": 15,
                    "air_temp": 15.2,
                    "dewpt": 4.3,
                    "press": 1010.7,
                    "press_qnh": 1010.7,
                    "press_msl": 1010.7,
                    "press_tend": "-",
                    "rain_trace": "0.0",
                    "rel_hum": 48,
                    "sea_state": "-",
                    "swell_dir_worded": "-",
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": "10",
                    "weather": "-",
                    "wind_dir": "WSW",
                    "wind_spd_kmh": 20,
                    "wind_spd_kt": 11
                },
                {
                    "sort_order": 9,
                    "wmo": 94767,
                    "name": "Sydney Airport",
                    "history_product": "IDN60901",
                    "local_date_time": "10/09:00pm",
                    "local_date_time_full": "20230410210000",
                    "aifstime_utc": "20230410110000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": 9.5,
                    "cloud": "Mostly clear",
                    "cloud_base_m": 2000,
                    "cloud_oktas": 2,
                    "cloud_type_id": 35,
                    "cloud_type": "-",
                    "delta_t": 5.0,
                    "gust_kmh": 28,
                    "gust_kt": 15,
                    "air_temp": 15.0,
                    "dewpt": 4.1,
                    "press": 1010.7,
                    "press_qnh": 1010.7,
                    "press_msl": 1010.7,
                    "press_tend": "-",
                    "rain_trace": "0.0",
                    "rel_hum": 48,
                    "sea_state": "-",
                    "swell_dir_worded": "-",
                    "swell_height": None,
                    "swell_period": None,
                    "vis_km": "40",
                    "weather": "Fine",
                    "wind_dir": "WSW",
                    "wind_spd_kmh": 22,
                    "wind_spd_kt": 12
                },
            ]
        }
    }
    '''assert get_processed_data(origin_object) == {
        "observations": {
            "data": [
                {
                    "sort_order": 0,
                    "wmo": 94769,
                    "name": "Fort Denison",
                    "history_product": "IDN60901",
                    "local_date_time": "10/03:00am",
                    "local_date_time_full": "20230310030000",
                    "aifstime_utc": "20230309160000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": "yes",
                    "cloud": "yes",
                    "cloud_base_m": "yes",
                    "cloud_oktas": "yes",
                    "cloud_type_id": "yes",
                    "cloud_type": "yes",
                    "delta_t": "yes",
                    "gust_kmh": 17,
                    "gust_kt": 9,
                    "air_temp": "yes",
                    "dewpt": "yes",
                    "press": "yes",
                    "press_qnh": "yes",
                    "press_msl": "yes",
                    "press_tend": "yes",
                    "rain_trace": "yes",
                    "rel_hum": "yes",
                    "sea_state": "yes",
                    "swell_dir_worded": "yes",
                    "swell_height": "yes",
                    "swell_period": "yes",
                    "vis_km": "yes",
                    "weather": "yes",
                    "wind_dir": "WNW",
                    "wind_spd_kmh": 15,
                    "wind_spd_kt": 8
                },
                {
                    "sort_order": 1,
                    "wmo": 94769,
                    "name": "Fort Denison",
                    "history_product": "IDN60901",
                    "local_date_time": "10/02:30am",
                    "local_date_time_full": "20230310023000",
                    "aifstime_utc": "20230309153000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": "yes",
                    "cloud": "yes",
                    "cloud_base_m": "yes",
                    "cloud_oktas": "yes",
                    "cloud_type_id": "yes",
                    "cloud_type": "yes",
                    "delta_t": "yes",
                    "gust_kmh": 17,
                    "gust_kt": 9,
                    "air_temp": "yes",
                    "dewpt": "yes",
                    "press": "yes",
                    "press_qnh": "yes",
                    "press_msl": "yes",
                    "press_tend": "yes",
                    "rain_trace": "yes",
                    "rel_hum": "yes",
                    "sea_state": "yes",
                    "swell_dir_worded": "yes",
                    "swell_height": "yes",
                    "swell_period": "yes",
                    "vis_km": "yes",
                    "weather": "yes",
                    "wind_dir": "W",
                    "wind_spd_kmh": 15,
                    "wind_spd_kt": 8
                },
                {
                    "sort_order": 2,
                    "wmo": 94769,
                    "name": "Fort Denison",
                    "history_product": "IDN60901",
                    "local_date_time": "10/02:00am",
                    "local_date_time_full": "20230310020000",
                    "aifstime_utc": "20230309150000",
                    "lat": -33.9,
                    "lon": 151.2,
                    "apparent_t": "yes",
                    "cloud": "yes",
                    "cloud_base_m": "yes",
                    "cloud_oktas": "yes",
                    "cloud_type_id": "yes",
                    "cloud_type": "yes",
                    "delta_t": "yes",
                    "gust_kmh": 15,
                    "gust_kt": 8,
                    "air_temp": "yes",
                    "dewpt": "yes",
                    "press": "yes",
                    "press_qnh": "yes",
                    "press_msl": "yes",
                    "press_tend": "yes",
                    "rain_trace": "yes",
                    "rel_hum": "yes",
                    "sea_state": "yes",
                    "swell_dir_worded": "yes",
                    "swell_height": "yes",
                    "swell_period": "yes",
                    "vis_km": "yes",
                    "weather": "yes",
                    "wind_dir": "WNW",
                    "wind_spd_kmh": 13,
                    "wind_spd_kt": 7
                }
            ]
        }
    }'''
    assert get_processed_data(origin_object)['observations']['data'] == [{
        'wmo': 94767,
        'name': 'Sydney Airport',
        'local_date_time': '20230410220000',
        'apparent_temp': 10.0,
        'cloud': 'Cloudy',
        'cloud_oktas': 8,
        'gust_kmh': 24,
        'air_temp': 14.8,
        'pressure': 1010.8,
        'rain_trace_since_9am': '0.0',
        'rel_humidity': 50,
        'visibility_km': '10',
        'wind_direction': 'WSW',
        'wind_speed_kmh': 19
    }, {
        'wmo': 94767,
        'name': 'Sydney Airport',
        'local_date_time': '20230410213000',
        'apparent_temp': 10.1,
        'cloud': 'Cloudy',
        'cloud_oktas': 8,
        'gust_kmh': 28,
        'air_temp': 15.2,
        'pressure': 1010.7,
        'rain_trace_since_9am': '0.0',
        'rel_humidity': 48,
        'visibility_km': '10',
        'wind_direction': 'WSW',
        'wind_speed_kmh': 20
    }, {
        'wmo': 94767,
        'name': 'Sydney Airport',
        'local_date_time': '20230410210000',
        'apparent_temp': 9.5,
        'cloud': 'Mostly clear',
        'cloud_oktas': 2,
        'gust_kmh': 28,
        'air_temp': 15.0,
        'pressure': 1010.7,
        'rain_trace_since_9am': '0.0',
        'rel_humidity': 48,
        'visibility_km': '40',
        'wind_direction': 'WSW',
        'wind_speed_kmh': 22
    }]
